apiVersion: apps/v1
kind: Deployment
metadata:
    name: customer-deployment
    labels:
        app: customer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: customer
    template:
        metadata:
            labels:
                app: customer
        spec:
            containers:
                - name: customer
                  image: sadeepabacr.azurecr.io/customer-service:latest
                  ports:
                      - containerPort: 8000
