apiVersion: v1
kind: Service
metadata:
    name: customer-service
spec:
    selector:
        app: customer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
    type: ClusterIP
